C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
g.region
g.region
g.proj
g.region -p
g.proj -p
g.region -p
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\ue5\OpenSourceGIS_exercise5\ex4_import_data.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
v.colors map=iso_bus@PERMANENT use=cat color=aspectcolr
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
db.tables
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
