C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
g.region
g.region
g.proj
g.region -p
g.proj -p
g.region -p
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
C:\Users\jocho\Desktop\opengis\project\python\dat_script_0_0.py
